//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Report.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style media=&quot;screen&quot;&gt;
        ///body{
        ///  padding: 0;margin: 0;
        ///  font-family: monospace;
        ///}
        ///h2{
        ///  font-family: monospace;
        ///}
        ///h3{
        ///  font-family: monospace;
        ///}
        ///hr{
        ///  border: none;
        ///  border-top: 1px solid #ccc;
        ///}
        ///ul{
        ///  padding: 0;
        ///}
        ///.header{
        ///  background: #E6E6E6;
        ///  border-bottom: 1px solid #D6D6D6;
        ///  padding: 1px 15px;
        ///  color: #717171;
        ///  font-family: monospace;
        ///}
        ///.container{
        ///  padding: 20px;
        ///}
        ///.feature{
        ///  border: 1px solid #CECECE;
        ///  padding: 30px;
        ///  box-shadow: 1px 1px 1px 1px #E0E0E0;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html_template {
            get {
                return ResourceManager.GetString("html_template", resourceCulture);
            }
        }
    }
}
